[package]
name = "fluids"
version = "0.1.0"
edition = "2021"
description = "Modeling of continuous substance flow and behavior under various physical conditions."

[dependencies]
#Not sure that we will use this
#bevy = "0.15"
