[package]
name = "electromagnetism"
version = "0.1.0"
edition = "2021"
description = "Systems modeling electromagnetic phenomena and their interactions across the universe."

[dependencies]
bevy = "0.15"
