[profile.dev]
split-debuginfo = "unpacked"
opt-level = 1
debug = 1
incremental = true

# Optimize dependencies for faster builds
[profile.dev.package."*"]
opt-level = 3
debug = false

# Bevy-specific optimizations
[profile.dev.package.bevy]
opt-level = 3
debug = false

# Fast dev profile for quick iteration
[profile.dev-fast]
inherits = "dev"
opt-level = 0
debug = false
incremental = true

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Ctarget-feature=+crt-static"]

# Build optimizations
[build]
jobs = 8